
title: YamanoItsuki
email: ituyama01@outlook.com


url: "https://ituyama.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl : /
# Build settings
layout: default
plugins:
  - jekyll-feed

permalink: /:month/:day/:minute
gist:
  noscript: false
